import { HttpAgent, type Message } from "@ag-ui/client";
import { useEffect, useMemo, useRef, useState } from "react";
import Markdown from "react-markdown";

import { readState } from "./agui";

/** Session state as the stream describes it: no payloads, one line per key. */
type StateEntry = { kind: string | null; tool?: string; bytes?: number };

/** The line a minimal client prints. Every activity carries one, generated by
 * the same code the bundled Chainlit host renders, so the two cannot drift. A
 * client with opinions reads the fields beside it instead. */
function shown(content: any): string {
  if (typeof content?.display === "string") return content.display;
  // state.consumed carries one receipt per parameter, each with its own line.
  if (content?.received) {
    return Object.entries<any>(content.received)
      .map(([parameter, receipt]) => `${parameter} ${receipt.display}`)
      .join("   ·   ");
  }
  return JSON.stringify(content);
}

/** A tool result on one line. The whole thing is in the thread route if a
 * client wants it; this is the glance. */
function summarise(result: string): string {
  const line = result.replace(/\s+/g, " ").trim();
  return line.length > 140 ? `${line.slice(0, 140)}…` : line;
}

/** ext-apps `LATEST_PROTOCOL_VERSION`, which the view's SDK checks. */
const UI_PROTOCOL_VERSION = "2026-01-26";

/** A tool's `ui://` bundle, mounted and driven over MCP Apps `ui/*`.
 *
 * This is the host end of the same JSON-RPC-over-postMessage protocol Claude,
 * ChatGPT, Goose and VS Code implement — the view's end is the standard
 * `@modelcontextprotocol/ext-apps` SDK, wrapped by `@developmentseed/mcp-view`.
 * The exchange is four messages:
 *
 *     view "ui/initialize"                 -> host info and capabilities
 *     view "ui/notifications/initialized"  -> host pushes tool-input, then
 *                                             tool-result (that order is
 *                                             required, and the view only
 *                                             needs the second)
 *     view "ui/message"                    -> a turn back into the chat
 *
 * `src` is the view route rather than `srcdoc`, so the bundle really is fetched
 * over HTTP — that route exists because a bundle is hundreds of kilobytes and
 * does not change between turns. `allow-scripts` without `allow-same-origin`
 * gives the frame an opaque origin: it can run, and it can reach nothing.
 */
function View({
  uri,
  data,
  onMessage,
}: {
  uri: string;
  data: unknown;
  onMessage: (text: string) => void;
}) {
  const frame = useRef<HTMLIFrameElement>(null);
  const [toolset, view] = uri.replace("ui://", "").split("/");
  // The turn's data never changes once rendered, but the listener is mounted
  // once — so it reads through a ref rather than closing over the first value.
  const latest = useRef(data);
  latest.current = data;
  const reply = useRef(onMessage);
  reply.current = onMessage;

  useEffect(() => {
    const iframe = frame.current;
    if (!iframe) return;
    const post = (message: unknown) =>
      iframe.contentWindow?.postMessage(message, "*");

    function handle(event: MessageEvent) {
      if (event.source !== iframe?.contentWindow) return;
      const message = event.data;
      if (!message || message.jsonrpc !== "2.0") return;

      if (message.method === "ui/initialize") {
        post({
          jsonrpc: "2.0",
          id: message.id,
          result: {
            protocolVersion: UI_PROTOCOL_VERSION,
            hostInfo: { name: "agui-chat-example", version: "1.0.0" },
            hostCapabilities: { message: { text: {} } },
            hostContext: {},
          },
        });
      } else if (message.method === "ui/notifications/initialized") {
        post({
          jsonrpc: "2.0",
          method: "ui/notifications/tool-input",
          params: { arguments: {} },
        });
        post({
          jsonrpc: "2.0",
          method: "ui/notifications/tool-result",
          params: { content: [], structuredContent: latest.current },
        });
      } else if (message.method === "ui/message" && message.id !== undefined) {
        const text = (message.params?.content ?? [])
          .filter((block: any) => block?.type === "text")
          .map((block: any) => block.text)
          .join("");
        if (text) reply.current(text);
        post({ jsonrpc: "2.0", id: message.id, result: {} });
      }
    }

    window.addEventListener("message", handle);
    return () => window.removeEventListener("message", handle);
  }, []);

  return (
    <iframe
      ref={frame}
      className="view"
      title={uri}
      src={`/api/views/${toolset}/${view}`}
      sandbox="allow-scripts"
    />
  );
}

export function Chat() {
  // The reference client, not a parser of our own: `HttpAgent` POSTs a
  // `RunAgentInput`, runs the SSE through `verifyEvents`, and applies each
  // event to `messages` and `state`. If this server emitted anything the
  // protocol disallows, the run would fail here rather than render wrongly.
  const agent = useMemo(
    () => new HttpAgent({ url: "/api/runs", threadId: crypto.randomUUID() }),
    [],
  );
  const log = useRef<HTMLDivElement>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [state, setState] = useState<Record<string, StateEntry>>({});
  const [opened, setOpened] = useState<{ key: string; text: string } | null>(null);
  const [running, setRunning] = useState(false);
  const busy = useRef(false);
  const [question, setQuestion] = useState(
    "find rainfall datasets and clip chirps to that area",
  );

  useEffect(() => {
    log.current?.scrollTo({ top: log.current.scrollHeight });
  }, [messages]);

  /** Run one turn. Called by the form, and by a view over `ui/message`.
   *
   * A ref rather than the `running` state for the guard: a view's button is
   * driven from a listener mounted once, so it closes over the first render's
   * value of anything held in state and would happily start a second turn on
   * top of the first.
   */
  async function run(text: string) {
    if (!text || busy.current) return;
    busy.current = true;
    setRunning(true);
    agent.addMessage({ id: crypto.randomUUID(), role: "user", content: text });
    setMessages([...agent.messages]);
    try {
      // One subscriber, called after each event is applied. Rendering from
      // `messages` rather than from the events is the point of the library:
      // an activity *is* a message, so it already sits where it belongs.
      await agent.runAgent(undefined, {
        onEvent: ({ messages }) => {
          setMessages([...messages]);
        },
        // Session state is ours, not AG-UI's `state` — see the README. It
        // arrives on the standard channel carrying `{kind, tool, bytes}`.
        onStateSnapshotEvent: ({ event }) => {
          setState((event.snapshot ?? {}) as Record<string, StateEntry>);
        },
      });
    } catch (error) {
      agent.addMessage({
        id: crypto.randomUUID(),
        role: "assistant",
        content: `client error: ${String(error)}`,
      });
      setMessages([...agent.messages]);
    } finally {
      busy.current = false;
      setRunning(false);
    }
  }

  function ask(submitted: React.FormEvent) {
    submitted.preventDefault();
    const text = question.trim();
    setQuestion("");
    void run(text);
  }

  async function open(key: string) {
    const entry = await readState(agent.threadId, key);
    setOpened({ key, text: JSON.stringify(entry.value) });
  }

  // The one answer still being written, so the caret marks where tokens are
  // landing rather than trailing every reply the thread has ever held.
  const writing = running
    ? messages.reduce<string | null>(
        (last, message) => (message.role === "assistant" ? message.id : last),
        null,
      )
    : null;

  return (
    <main>
      <div className="chat">
        <header>
          <b>mcp_agent_api</b>
          {/* The two colours are the whole point of the wire: blue is what
              AG-UI gives any client, amber is what this runtime adds on top
              of it. Naming them beats leaving a reader to infer it. */}
          <span className="legend">
            <i className="swatch tool" /> AG-UI
            <i className="swatch activity" /> receipts and views
            <span className="dim">· thread {agent.threadId.slice(0, 8)}</span>
          </span>
        </header>

        <div className="log" ref={log}>
          {messages.map((message) =>
            message.role === "user" || message.role === "assistant" ? (
              <div key={message.id} className={`said ${message.role}`}>
                {/* Models answer in markdown whether or not you asked, and a
                    half-written stream is half-written markdown — an unclosed
                    ** or a table with one row. react-markdown re-parses each
                    delta, so it degrades to plain text rather than showing
                    syntax, and renders no raw HTML, which matters when the
                    text came from a model. */}
                <Markdown>{String(message.content ?? "")}</Markdown>
                {(message as any).toolCalls?.map((call: any) => (
                  // <details> rather than state: collapsing is what the
                  // element is for, and the keyboard and screen-reader
                  // behaviour comes with it.
                  <details key={call.id} className="tool">
                    <summary>
                      <code>{call.function.name}</code>
                    </summary>
                    <pre>{call.function.arguments || "{}"}</pre>
                  </details>
                ))}
                {message.id === writing ? <i className="caret" /> : null}
              </div>
            ) : message.role === "tool" ? (
              <details key={message.id} className="tool">
                <summary>
                  <span className="dim">result</span>{" "}
                  {summarise(String(message.content ?? ""))}
                </summary>
                <pre>{String(message.content ?? "")}</pre>
              </details>
            ) : message.role === "activity" ? (
              <details key={message.id} className="activity">
                <summary>
                  <em>{(message as any).activityType}</em>
                </summary>
                <span>{shown((message as any).content)}</span>
                {(message as any).content?.uri ? (
                  <View
                    uri={(message as any).content.uri}
                    data={(message as any).content.data}
                    // `ui/message` starts the turn rather than filling the
                    // box: the bundled Chainlit host sends it, and a button
                    // that only types for you is a view that cannot act.
                    onMessage={run}
                  />
                ) : null}
                <pre className="dim">
                  {JSON.stringify((message as any).content, null, 2)}
                </pre>
              </details>
            ) : null,
          )}
          {messages.length === 0 ? (
            <p className="dim">
              Four MCP servers are connected: dataset search, raster clipping
              with a <code>ui://</code> view, contour smoothing the deployment
              cannot offer, and a third-party server that knows nothing about
              any of this. Try{" "}
              <b>find rainfall datasets and clip chirps to that area</b>, or ask
              about <b>contours</b>.
            </p>
          ) : null}
        </div>

        <form onSubmit={ask}>
          <input
            value={question}
            onChange={(changed) => setQuestion(changed.target.value)}
            placeholder="ask something"
            autoFocus
          />
          <button disabled={running || !question.trim()}>
            {running ? "…" : "send"}
          </button>
        </form>
      </div>

      <aside>
        <h2>session state</h2>
        <p className="dim">
          What the tools exchanged without the model reading it. The stream
          carries this much per key and no payload; the value is a fetch away.
        </p>
        {Object.entries(state).map(([key, entry]) => (
          <button key={key} className="key" onClick={() => open(key)}>
            <code>{key}</code>
            <span className="dim">
              {entry.kind ?? "untyped"} · {entry.bytes} bytes · from {entry.tool}
            </span>
          </button>
        ))}
        {opened ? (
          <pre>
            <b>GET /threads/…/state/{opened.key}</b>
            {"\n\n"}
            {opened.text.slice(0, 600)}
            {opened.text.length > 600 ? "…" : ""}
          </pre>
        ) : null}
      </aside>
    </main>
  );
}
